apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: nginx-better
  ports:
    - protocol: TCP
      port: 80 # Port the service is listening on
      targetPort: 8080 # Port the container is listening on (if unset, defaults to equal port value)

